apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    concurrency: 1
    push: false
    tryImportMissing: false
    useDockerCLI: false
  artifacts:
    - image: xuantho2811/ticket-auth
      context: auth
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: xuantho2811/ticket-client-js
      context: client
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "**/*.js"
